baseURL: "https://powercore2000.github.io/"
languageCode: "en-us"
title: "Powercore's Place in Space"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Powercore's Place in Space"
  description: Powercore's Place in Space
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
     disableThemeToggle: true
     defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Corvalis C's Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "My username is Powercore2000, but you may also know me as..."
    title: "Corvalis C."
    subtitle: "I develop games and gamify software development"
    content: "Welcome to my blog where I catalog my journey making all things software related. Here you can see my work on game projects, practice my full stack development, and follow my journey of constant improvement and life long learning. Hope you enjoy your stay in my place in space!"
    image: /images/hero.png
    backgroundImage: /images/background.gif
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/documents/CorvalisC-entry-software-cv.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-youtube
          url: https://www.youtube.com/@powercore2000
        - icon: fab fa-github
          url: https://github.com/powercore2000
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/corvalis-c-191851132/
      customIcons:
        - icon: /fav.png
          url: https://linktr.ee/powercore2000

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/Placeholder.png
    image_1: /images/me_1.png
    image_2: /images/me_2.png
    content: |-
     Hello! I'm Corvalis Cohen, a software engineer, and founder of Silvaroc Studios L.L.C. I work in a self employed capacity while pursuing my undergraduate Computer Science degree. Currently looking for work to both finance my education and gain more applied experience in the work force. 

     My current expertise consists of 5+ years of software development experience from hobbyist projects, freelance software work, Unity virtual production, game development, and full stack web development. I also have experience in Development Operations for game and web development environments. 

     I possess excellent communication, coordination, and cooperation skills from my years of community work with the Young Male Scholars foundation and Women's Leadership Project. Along with superb administrative and documentation skills from the years of maintaining documentation from my projects, handling my business's administrative needs, handling the production of several long-term projects and collaborating with contractors and volunteers.

     I'm looking for a wide variety of remote assignments I can take while pursing my degree. My preferred fields of work are those in software engineering, development operations, and other technical positions with my current qualifications. I always looking forward to further job training, learning new technologies as I work, gain new experiences, and working with teams of a variety people. I look forward to working with you!
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C#"
        - "C++"
        - "Unity Engine"
        - "Unreal Engine"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Typescript"
        - "Node.js"
        - "Express.js"
        - "Docker"
        - "Dev-Ops"
        - "OpenAi API"
        - "REST/SOAP APIs"

 
  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Lead Software Engineer"
        company: "Silvaroc Studios LLC"
        #companyUrl: "https://example.com"
        date: "Aug 2021 - Present"
        content: "Oversaw the design and development of all software and virtual production projects. Responsibilities included:"
        content:  |
            - Designing and implementing C#/C++ APIs
            - Built asynchronous serialization systems to read/write information
            -Lead the design and project management of all software products
            - Maintained project repositories through source control solutions
            (GitHub, Perforce, Plastic SCM, e.c.t)
            - Quality tested programs for optimization with DevOps principles,
            using Unit Testing techniques, and CI/CD driven development

      - job: "Full Stack Developer"
        company: "Kiira Health"
        companyUrl: "https://example.com"
        date: "Sept 2022 - Oct 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          #content: I worked as a software developer for more than one year in Amazon.
        content: 
          |
          - Developed Restful APIs and web-hooks on the Firebase platform
          To handle asynchronous behavior in a server-less architecture
          - Maintained a React Native mobile apps front-end and back-end
          behavior, and build process on Android and IOS platforms
          - Collaborated with other engineers and designers to ensure clarity
          and cohesion with Agile/SCRUM principles in a JIRA environment

      - job: "Online Private Instructor"
        company: "Id Tech"
        companyUrl: "https://example.com"
        date: "May 2022 - Sep 2022 and March 2023 - Present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
            - Applied knowledge of the Unity Engine and C# to a wide variety of
            technical situations and design needs for students.
            - Taught over 50 lessons with students and clients of a wide variety
            of skill levels and backgrounds
            - Curated a curriculum focused on teaching algorithmic design, and
            good collaborative coding standards

      - job: "Freelance Software Engineering"
        company: "Freelance"
        companyUrl: "https://example.com"
        date: "Jan 2018 - Current"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: 
          |
          - Produced a wide variety of applications, tools, and 
          services on platforms such as AR/VR, Android/IOS, HTML5, etc.
          - Collaberated with software engineering teams with various sizes, compositions, and 
          production workflows (Agile, Waterfall, SCRUM, ect)
          - Developed performative and scalabe systems with proprietary and 3rd party 
           technologies in several game engines and tech stacks
          - Gave consultation services to a vairety of software projects and production teams across disiplines (Education, Game Development, ect)

      - job: "Web Contracter"
        company: "Vype Entertainment"
        companyUrl: "https://example.com"
        date: "Feb 2023 - Present"
        #content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "California State University Dominguez Hills"
          url: "https://www.csudh.edu/"
        date: "2018 - Current"
        #GPA: "3.9 out of 5.0"
        content: |-
          **DEGREE IN PROGRESS** Expected date: 2025
          

      - title: "High School Diplima"
        school:
          name: "Gardena Senior High School"
        GPA: "3.5 out of 4.0"


  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: GMTK 2022 Game Jam
        content: "Worked with two teams to complete two games in 48 hours. Placed #2864 and #4994 out of over 6,000 entries!"
        featured:
        url: https://powercore2000.itch.io/
      - title: Jingle Jam Game Jam 2022
        content: Placed 27th out of 66 entries
        url: https://itch.io/jam/yogscast-game-jam-2021/rate/1312546
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Cyberspace Crusade
        content: A virtual production platform made in Unity for creating animation, cinematics, and game dev logs
        


  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Hugo Portfolio Website
        content: Utilized the Hugo framework and modified hugo-profiles theme to create the online portfolio used now! Hosted on github Pages
        image: /images/projects/website-thumbnail.jpg
        badges:
          - "Hugo"
          - "Github Pages"
          - "Javascript"
          - "HTML"
          - "CSS"
        links:
          - icon: fab fa-github
            url: https://github.com/powercore2000/powercore2000.github.io

      - title: Cyberspace Crusade
        content: A virtual production platform made in Unity for creating animation, cinematics, and game dev logs. 
                Used on the powercore2000 youtube channel
        image: /images/projects/cyberspace-crusade.jpg
        badges:
          - "Unity"
          - "C#"
          - "Motion Capture"
        links:
          - icon: fab fa-youtube
            url: http://youtube.com/@powercore2000

      - title: GPT to Unity
        content: A cool project I worked on, and need to replace this placeholder text for!
        image: /images/projects/gpt-to-unity-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "ASP.Net Core"
          - "Networking"
          - "TCP/UDP"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

      - title: 2D RPGs
        #content: A cool project I worked on, and need to replace this placeholder text for!
        content: My first game experiments with Unity's 2d animation system.
        image: /images/projects/2d-rpg-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Unity"
          - "C#"
          - "Pixel Art"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2           

      - title: Combo Katana
        content: Created a micro game with unreal engine. Used the Animation blueprint system to handle attack combos and transition conditions.
        image: /images/projects/combo-katana-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Unreal Engine"
          - "C++"
          - "Blueprints"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2    

      - title: Heros of RNG
        content: One of the GMTK 2022 entries  worked on! A RNG and dice based dungeon crawler. 
        image: /images/projects/heros-of-rng-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Unity"
          - "C#"
          - "Game Jam"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2         

      - title: Xcom 2 Modding
        content: Modded Xcom 2 to expand the armor roster
        image: /images/projects/xcom-mod-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Unreal Engine"
          - "C++"
          - "Modding"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2         
      
      - title: Hosting Foundary VTT
        content: Self hosted my own foundary VTT server to host tabletop RPG sessions
        image: /images/projects/foundary-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Docker"
          - "Server Managment"
          - "Powershell"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2         

      - title: Action Lab
        content: An experimental 3rd person shooter project built out of Cyberspace Crusade
        image: /images/projects/action-lab-thumbnail.jpg
        #featured:
         # name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        badges:
          - "Unity"
          - "C#"
          - "Game-Project"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/HugoProfileV2         


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: CorvalisC@gmail.com
    btnName: Mail me
    formspree:
       enable: true # `contact.email` value will be ignored
       formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
       emailCaption: "Enter your email address"
       messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://www.linkedin.com/in/corvalis-c-191851132/
      linkedin: https://www.linkedin.com/in/corvalis-c-191851132/
      twitter: https://twitter.com/powercore2000
      instagram: https://www.instagram.com/powercore2000/
      #facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
